// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUnCHnCE5Uko0KHDvHkeeZSwCqviPwqlA',
    appId: '1:667927832152:web:569e67e55024e100420c2d',
    messagingSenderId: '667927832152',
    projectId: 'temphumid-7f823',
    authDomain: 'temphumid-7f823.firebaseapp.com',
    databaseURL: 'https://temphumid-7f823-default-rtdb.firebaseio.com',
    storageBucket: 'temphumid-7f823.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPJ821iqZSmf_mEPKO3YRfW03LtEXV_0',
    appId: '1:667927832152:android:3ffcbc583d43ab33420c2d',
    messagingSenderId: '667927832152',
    projectId: 'temphumid-7f823',
    databaseURL: 'https://temphumid-7f823-default-rtdb.firebaseio.com',
    storageBucket: 'temphumid-7f823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXMqBuMM0QBZM5agDq6MYtd1YlZ0q8oQ',
    appId: '1:667927832152:ios:5f9cdd64523752b1420c2d',
    messagingSenderId: '667927832152',
    projectId: 'temphumid-7f823',
    databaseURL: 'https://temphumid-7f823-default-rtdb.firebaseio.com',
    storageBucket: 'temphumid-7f823.appspot.com',
    iosBundleId: 'com.example.humidtempApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYXMqBuMM0QBZM5agDq6MYtd1YlZ0q8oQ',
    appId: '1:667927832152:ios:5f9cdd64523752b1420c2d',
    messagingSenderId: '667927832152',
    projectId: 'temphumid-7f823',
    databaseURL: 'https://temphumid-7f823-default-rtdb.firebaseio.com',
    storageBucket: 'temphumid-7f823.appspot.com',
    iosBundleId: 'com.example.humidtempApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUnCHnCE5Uko0KHDvHkeeZSwCqviPwqlA',
    appId: '1:667927832152:web:af614c780625799f420c2d',
    messagingSenderId: '667927832152',
    projectId: 'temphumid-7f823',
    authDomain: 'temphumid-7f823.firebaseapp.com',
    databaseURL: 'https://temphumid-7f823-default-rtdb.firebaseio.com',
    storageBucket: 'temphumid-7f823.appspot.com',
  );
}
